
    @Test
    public void into0() throws Exception {
        Context context = PowerMockito.mock(Context.class);
        Action pushAction = PowerMockito.mock(PushAction.class);
        PushContext.InnerState innerState = PowerMockito.mock(PushContext.InnerState.class);
        PushContext pushContext = new PushContext(context, pushAction, innerState);
        pushContext.onConnected(Mockito.anyString(),Mockito.anyString(),Mockito.anyInt(),Mockito.anyLong(),Mockito.anyLong());
        Mockito.verify(pushAction, Mockito.times(1)).publicKey(Mockito.any(ResponseCallback.class));
    }
报错

		org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
		Invalid use of argument matchers!
		1 matchers expected, 5 recorded:
		-> at com.xtc.im.core.push.state.ConnectedStateTest.into0(ConnectedStateTest.java:52)
		-> at com.xtc.im.core.push.state.ConnectedStateTest.into0(ConnectedStateTest.java:52)
		-> at com.xtc.im.core.push.state.ConnectedStateTest.into0(ConnectedStateTest.java:52)
		-> at com.xtc.im.core.push.state.ConnectedStateTest.into0(ConnectedStateTest.java:52)
		-> at com.xtc.im.core.push.state.ConnectedStateTest.into0(ConnectedStateTest.java:52)

修改

  	public void into0() throws Exception {
        Context context = PowerMockito.mock(Context.class);
        Action pushAction = PowerMockito.mock(PushAction.class);
        PushContext.InnerState innerState = PowerMockito.mock(PushContext.InnerState.class);
        PushContext pushContext = new PushContext(context, pushAction, innerState);
        pushContext.onConnected(“”,“”,1,1L,1L);
        Mockito.verify(pushAction, Mockito.times(1)).publicKey(Mockito.any(ResponseCallback.class));
    }


